= Real Time Calculator

Real Time Calculator is a basic calculator with a real-time display of calculations, allowing users to perform addition, subtraction, multiplication, and division. It updates the result dynamically as users input numbers and operators, ensuring an intuitive and responsive user experience.

== Table of contents

* <<related-content,Related content>>
* <<technologies-and-tools,Technologies>>
* <<installation,Installation>>
* <<demonstration,Demonstration>>
* <<status,Status>>
** <<features,Features>>
** <<issues,Issues>>
** <<changelog,Changelog>>
** <<to-do,To-do>>
* <<contributing,Contributing>>
* <<licence,Licence>>
* <<contact,Contact>>

== Related content

* https://www.theodinproject.com/paths/foundations/courses/foundations/lessons/calculator[Calculator Project] from The Odin Project

=== Assignment

Here are some use cases (expectations about your project):

. Your calculator is going to contain functions for all of the basic math operators you typically find on calculators, so start by creating functions for the following items and testing them in your browser's console:
* add
* subtract
* multiply
* divide
. A calculator operation will consist of a number, an operator, and another number. For example, 3 + 5. Create three variables, one for each part of the operation. You'll use these variables to update your display later.
. Create a new function `operate` that takes an operator and two numbers and then calls one of the above functions on the numbers.
. Create a basic HTML calculator with buttons for each digit and operator (including `=`).
* Don't worry about making them functional just yet.
* There should also be a display for the calculator. Go ahead and fill it with some dummy numbers so it looks correct.
* Add a "clear" button.
. Create the functions that populate the display when you click the digit buttons. You should store the content of the display (the number) in a variable for use in the next step.
. Make the calculator work! You'll need to store the first and second numbers input by the user and then `operate()` on them when the user presses the `=` button, according to the operator that was selected between the numbers.
* You should already have the code that can populate the display, so once `operate` has been called, update the display with the result of the operation.
* This is the hardest part of the project. You need to figure out how to store all the values and call the `operate` function with them. Don't feel bad if it takes you a while to figure out the logic.
. Gotchas: watch out for and fix these bugs if they show up in your code:
* *Your calculator should not evaluate more than a single pair of numbers at a time.* Example: you enter a number (`12`), followed by an operator button (`+`), a second number button (`7`), and a second operator button (`-`). Your calculator should then do the following: first, evaluate the initial pair of numbers (`12 + 7`), then display the result of that calculation (`19`). Finally, use that result (`19`) as the first number in a new calculation, along with the next operator (`-`). An example of the behavior we're looking for can be seen in this https://mrbuddh4.github.io/calculator/[student's calculator live preview].
* You should round answers with long decimals so that they don't overflow the display.
* Pressing `=` before entering all of the numbers or an operator could cause problems!
* Pressing "clear" should wipe out any existing data. Make sure the user is really starting fresh after pressing "clear".
* Display a snarky error message if the user tries to divide by 0… and don't let it crash your calculator!
* Make sure that your calculator only runs an operation when supplied with two numbers and an operator by the user. Example: you enter a number (`2`), followed by an operator button (`+`). You press the operator button (`+`) a second consecutive time. Your calculator should not evaluate this as (`2 + 2`) and should not display the result (`4`). If consecutive operator buttons are pressed, your calculator should not run any evaluations, it should only take the last operator entered to be used for the next operation.

== Technologies and tools

image:https://img.shields.io/badge/html5-%23E34F26.svg?style=for-the-badge&logo=html5&logoColor=white[HTML5]
image:https://img.shields.io/badge/css3-%231572B6.svg?style=for-the-badge&logo=css3&logoColor=white[CSS3]
image:https://img.shields.io/badge/javascript-%23323330.svg?style=for-the-badge&logo=javascript&logoColor=%23F7DF1E[JavaScript]

== Installation

Launch the project in your browser through the .html file.

== Demonstration

https://dyrits.github.io/WEBDEV-TOP-RTC/[Try it!]

== Status

The project has been completed.

=== Features

The project is fully functional and meets the requirements of the assignment.

=== Issues

There is no current issue with this project.
Feel free to open an issue if you have any questions or comments.

=== Changelog

.**Version 1.00.01 (01/2025)**
[%collapsible]
====
The README has been updated.
====

.**Version 1.00.01 (05/2020)**
[%collapsible]
====
The first version of the project has been released.
====

=== To-do

The project is complete and will not be updated further.

== Contributing

Pull requests are welcome. For major changes, please open an issue first to discuss what you would like to change.
Please make sure to update tests as appropriate (if any).

== Licence

image:https://img.shields.io/github/license/Ileriayo/markdown-badges?style=for-the-badge[Licence,link=./LICENSE]

== Contact

Created by https://github.com/Dyrits[Dylan J. Gerrits].